# Source: https://raw.githubusercontent.com/zalando-incubator/kopf/242774942c5cbe5c236a439414ba42e45f79e644/peering.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterkopfpeerings.zalando.org
  labels:
    component: benji
  annotations:
    helm.sh/hook: crd-install
spec:
  scope: Cluster
  group: zalando.org
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: ClusterKopfPeering
    plural: clusterkopfpeerings
    singular: clusterkopfpeering
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kopfpeerings.zalando.org
  labels:
    component: benji
  annotations:
    helm.sh/hook: crd-install
spec:
  scope: Namespaced
  group: zalando.org
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: KopfPeering
    plural: kopfpeerings
    singular: kopfpeering
