dependencies:
      - name: postgresql
        version: 10.1.1
        repository: https://charts.bitnami.com/bitnami
        condition: postgresql.enabled
      - name: prometheus-pushgateway
        alias: pushgateway
        version: 1.5.0
        repository: https://prometheus-community.github.io/helm-charts
