timeZone: Europe/Berlin

benji:
  image:
    registry: docker.io
    repository: elementalnet/benji-k8s
    tag: latest
    pullPolicy: Always

  instance: benji

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configuration:
    configurationVersion: '1'
    databaseEngine: sqlite:////tmp/benji.sqlite
    defaultStorage: storage-1
    storages:
      - name: storage-1
        storageId: 1
        module: file
        configuration:
          path: /tmp/benji-data
    ios:
      - name: file
        module: file

  # Volumes and volume mounts can be used to mount Ceph configuration and credentials, backup sources or storages into
  # the Benji container.
  volumes:
    - name: ceph-etc
      configMap:
        name: ceph-etc
        defaultMode: 0444
    - name: ceph-client-admin-keyring
      secret:
        secretName: ceph-client-admin-keyring
        defaultMode: 0444

  volumeMounts:
    - name: ceph-etc
      mountPath: /etc/ceph/ceph.conf
      subPath: ceph.conf
      readOnly: true
    - name: ceph-client-admin-keyring
      mountPath: /etc/ceph/ceph.client.admin.keyring
      subPath: ceph.client.admin.keyring
      readOnly: true

  api:
    port: 7746
    replicas: 1
    threadsPerReplica: 10

operator:
  image:
    registry: docker.io
    repository: elementalnet/benji-k8s-operator
    tag: latest
    pullPolicy: Always

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

fsfreeze:
  enabled: false

  image:
    registry: docker.io
    repository: centos
    tag: 7
    pullPolicy: IfNotPresent

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

postgresql:
  enabled: false
  postgresqlUsername: benji
  postgresqlDatabase: benji
  postgresqlPassword: secret

pushgateway:
  image:
    registry: docker.io
    repository: prom/pushgateway
    tag: v0.8.0
    pullPolicy: IfNotPresent
  nameOverride: pushgateway
