---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: benjiversions.benji-backup.me
  labels:
    component: benji
  annotations:
    helm.sh/hook: crd-install
spec:
  scope: Namespaced
  group: benji-backup.me
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - bytesDeduplicated
                - bytesRead
                - bytesSparse
                - bytesWritten
                - date
                - duration
                - size
                - snapshot
                - storage
                - volume
                - persistentVolumeClaimName
              properties:
                bytesDeduplicated:
                  type: string
                bytesRead:
                  type: string
                bytesSparse:
                  type: string
                bytesWritten:
                  type: string
                date:
                  type: string
                duration:
                  type: integer
                size:
                  type: string
                snapshot:
                  type: string
                storage:
                  type: string
                volume:
                  type: string
                persistentVolumeClaimName:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              required:
                - protected
                - status
              properties:
                protected:
                  type: boolean
                status:
                  type: string
      additionalPrinterColumns:
        - name: PVC
          type: string
          description: Name of the backed up PVC
          jsonPath: .spec.volumeInfo.persistentVolumeClaimName
          priority: 0
        - name: Age
          type: date
          description: Creation date of the backupded PVC
          jsonPath: .spec.date
          priority: 0
        - name: Status
          type: string
          description: Status of the version
          jsonPath: .status.status
          priority: 0
        - name: Protected
          type: boolean
          jsonPath: .status.protected
          description: Protection status of this version
          priority: 0
        - name: Storage
          type: string
          jsonPath: .spec.storage
          description: Storage location
          priority: 1
        - name: Duration
          type: integer
          jsonPath: .spec.duration
          description: Backup duration in seconds
          priority: 1
        - name: Read
          type: string
          format: int64
          jsonPath: .spec.bytesRead
          description: Number of bytes read
          priority: 1
        - name: Written
          type: string
          format: int64
          jsonPath: .spec.bytesWritten
          description: Number of bytes written to storage
          priority: 1
  names:
    kind: BenjiVersion
    plural: benjiversions
    singular: benjiversion
    shortNames:
      - benjivs
      - benjiv

